### ISSUE TITLE
"Cancel all" button on GitHub UI

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/buildomat#29]
Sometimes I'll push a fix to an omicron PR and I know the currently running thing will fail anyway, or I don't care, so I cancel the jobs to free up the queue. But there are like 10 jobs, so it's a lot of clicking.

Here is the existing cancel button for a single job. If the cancel all button would go next to it, it would be good to be pretty explicit about what it does in the button label text. I wouldn't normally expect to be able to affect other jobs from inside that page.

![image](https://github.com/oxidecomputer/buildomat/assets/3612203/f11998ba-dfa1-4fab-8aa5-427c50eb3e42)

**Comment by david-crespo** [comment]
https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28#update-a-check-run

<img width="588" alt="image" src="https://github.com/oxidecomputer/buildomat/assets/3612203/0ff0b456-6961-4e51-bdc8-bbea110ddc39">

**Comment by jclulow** [comment]
I have attempted to fix this in 4ae0dc9fc1e6e300bba9f959ce264aad2754cdbd which is now deployed.  There will be two buttons, one of which will attempt to cancel things that are still running:

![cancels](https://github.com/oxidecomputer/buildomat/assets/304070/e7c664a0-391d-40eb-807a-540fda8a4ce8)

If it doesn't work for you when you try, please re-open the issue!
