### ISSUE TITLE
treat rotated log files (e.g. `*.log.0`) the same as `*.log`

### ISSUE THREAD

**Issue by iliana** [oxidecomputer/buildomat#57]
For example on https://buildomat.eng.oxide.computer/wg/0/details/01HXXBNPS6HR3X7BT9X3P0Y8XE/41gsBIUaozbpdtMxYqrdhsWOkOJAwHYYh50Emy4FvWxL4iOU/01HXYFDYPAWA2XZ0BFP0YSNBA1, log rotation kicked in and so it's difficult to view the logs.

I can work around this by futzing with the URL (changing the last path component to end in `.log` and adding `?format=x-bunyan`) but it'd be nice to have the rendered link.

**Comment by jclulow** [comment]
Thanks for providing an example link; saved me a lot of futzing about trying to find an example!

This is fixed as of 957aec36e25998fb68b4865bee11d407e5ddd92b which I have just deployed.  I confirmed I was able to view both the plain and regular view of the `*.log.0` files in your example.
